[package]

name = "shiplift"
version = "0.3.2"
authors = ["softprops <d.tangren@gmail.com>"]
description = "A Rust interface for maneuvering Docker containers"
documentation = "https://softprops.github.io/shiplift"
homepage = "https://github.com/softprops/shiplift"
repository = "https://github.com/softprops/shiplift"
keywords = ["docker", "unix", "containers", "hyper", "ship"]
license = "MIT"
openssl = false

# select features you would like to use
[features]
default = [ "openssl", "hyper-openssl" ]
# default = []

[dependencies]
byteorder = "1.0.0"
flate2 = "0.2"
hyper = "0.10"
hyperlocal = "0.3"
jed = "0.1"
log = "0.3"
rustc-serialize = "0.3"
tar = "0.4"
url = "0.5"
serde = "1.0"
serde_derive = "1.0"

hyper-openssl = { version = "0.2", optional = true }
openssl = { vesrion = "0.9", optional = true }

[dev-dependencies]
env_logger = "0.4.0"
