[package]

name = "shiplift"
version = "0.3.1"
authors = ["softprops <d.tangren@gmail.com>"]
description = "A Rust interface for maneuvering Docker containers"
documentation = "https://softprops.github.io/shiplift"
homepage = "https://github.com/softprops/shiplift"
repository = "https://github.com/softprops/shiplift"
keywords = ["docker", "unix", "containers", "hyper", "ship"]
license = "MIT"

[dependencies]
byteorder = "1.0.0"
flate2 = "0.2"
hyper = "0.10"
hyper-openssl = "0.2"
hyperlocal = "0.3"
jed = "0.1"
log = "0.3"
openssl = "0.9"
rustc-serialize = "0.3"
tar = "0.3"
url = "0.5"

[dev-dependencies]
env_logger = "0.4.0"
